//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeWorld.ADS.Migrations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeeWorld.ADS.Migrations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Drop Users Table
        ///
        ///DROP TABLE [Users].
        /// </summary>
        internal static string D0001 {
            get {
                return ResourceManager.GetString("D0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Drop Users Table
        ///
        ///DROP TABLE [Tokens].
        /// </summary>
        internal static string D0002 {
            get {
                return ResourceManager.GetString("D0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Drop Users Table
        ///
        ///DROP TABLE [Applications].
        /// </summary>
        internal static string D0003 {
            get {
                return ResourceManager.GetString("D0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Drop Builds Table
        ///
        ///DROP TABLE [Builds].
        /// </summary>
        internal static string D0004 {
            get {
                return ResourceManager.GetString("D0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Drop Groups Table
        ///
        ///DROP TABLE [Groups].
        /// </summary>
        internal static string D0005 {
            get {
                return ResourceManager.GetString("D0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Drop GroupApplications Table
        ///
        ///DROP TABLE [GroupApplications].
        /// </summary>
        internal static string D0006 {
            get {
                return ResourceManager.GetString("D0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Drop GroupUsers Table
        ///
        ///DROP TABLE [GroupUsers].
        /// </summary>
        internal static string D0007 {
            get {
                return ResourceManager.GetString("D0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Create Users Table
        ///
        ///CREATE TABLE [Users](
        ///	[Id] [int] IDENTITY(1,1) NOT NULL,
        ///	[EmailAddress] [varchar](250) NOT NULL,
        ///	[Password] [varchar](250) NOT NULL,
        ///	[Salt] [binary](8) NOT NULL,
        ///	[DateCreated] [datetime] NOT NULL DEFAULT (getdate()),
        ///	 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ( [Id] ASC ),
        ///	 CONSTRAINT [IX_Users_EmailAddress] UNIQUE NONCLUSTERED ( [EmailAddress] ASC)
        ///).
        /// </summary>
        internal static string U0001 {
            get {
                return ResourceManager.GetString("U0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Create Tokens Table
        ///
        ///CREATE TABLE [Tokens](
        ///	[Id] [int] IDENTITY(1,1) NOT NULL,
        ///	[Code] [varchar](50) NOT NULL,
        ///	[ExpiryDate] [datetime] NOT NULL,
        ///	[UserId] [int] NOT NULL,
        ///	CONSTRAINT [PK_Tokens] PRIMARY KEY CLUSTERED ( [Id] ASC)
        ///)
        ///
        ///ALTER TABLE [Tokens]  WITH CHECK ADD CONSTRAINT [FK_Tokens_Users] FOREIGN KEY([UserId])
        ///REFERENCES [Users] ([Id]) ON DELETE CASCADE.
        /// </summary>
        internal static string U0002 {
            get {
                return ResourceManager.GetString("U0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Create Applications Table
        ///
        ///CREATE TABLE [Applications](
        ///	[Id] [int] IDENTITY(1,1) NOT NULL,
        ///	[Name] [varchar](100) NOT NULL,
        ///	[DateCreated] [datetime] NOT NULL DEFAULT (getdate()),
        ///	[IconUrl] [varchar](250) NULL,
        ///	[Deleted] [bit] NOT NULL DEFAULT ((0)),
        ///	[Platform] [varchar](50) NOT NULL DEFAULT (&apos;iOS&apos;),
        ///	 CONSTRAINT [PK_Applications] PRIMARY KEY CLUSTERED ( [Id] ASC),
        ///	 CONSTRAINT [IX_Applications] UNIQUE NONCLUSTERED ( [Name] ASC)
        ///).
        /// </summary>
        internal static string U0003 {
            get {
                return ResourceManager.GetString("U0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Create Builds Table
        ///
        ///CREATE TABLE [Builds](
        ///	[Id] [int] IDENTITY(1,1) NOT NULL,
        ///	[ApplicationId] [int] NOT NULL,
        ///	[Type] [int] NOT NULL DEFAULT ((0)),
        ///	[VersionNumber] [varchar](50) NOT NULL,
        ///	[BuildNumber] [varchar](50) NOT NULL,
        ///	[DateCreated] [datetime] NOT NULL DEFAULT (getdate()),
        ///	[PackageUrl] [varchar](255) NOT NULL,
        ///	[SubmissionState] [int] NOT NULL,
        ///	[SubmissionNotes] [varchar](max) NULL,
        ///	[SubmissionDate] [datetime] NULL,
        /// CONSTRAINT [PK_Builds] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string U0004 {
            get {
                return ResourceManager.GetString("U0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Create Groups Table
        ///
        ///CREATE TABLE [Groups](
        ///	[Id] [int] IDENTITY(1,1) NOT NULL,
        ///	[Name] [varchar](100) NOT NULL,
        ///	[Enabled] [bit] NOT NULL  DEFAULT ((1)),
        ///	[DateCreated] [datetime] NOT NULL DEFAULT (getdate()),
        ///	[AlertStatus] [int] NOT NULL DEFAULT ((0)),
        ///	 CONSTRAINT [PK_Groups] PRIMARY KEY CLUSTERED ( [Id] ASC ),
        ///	 CONSTRAINT [IX_Groups] UNIQUE NONCLUSTERED ( [Name] ASC)
        ///)
        ///.
        /// </summary>
        internal static string U0005 {
            get {
                return ResourceManager.GetString("U0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Create GroupApplications Table
        ///
        ///CREATE TABLE [GroupApplications](
        ///	[GroupId] [int] NOT NULL,
        ///	[ApplicationId] [int] NOT NULL,
        ///	CONSTRAINT [PK_GroupApplications] PRIMARY KEY CLUSTERED ( [GroupId] ASC, [ApplicationId] ASC )
        ///)
        ///
        ///ALTER TABLE [GroupApplications]  WITH CHECK ADD  CONSTRAINT [FK_GroupApplications_Applications] FOREIGN KEY([ApplicationId])
        ///REFERENCES [Applications] ([Id]) ON DELETE CASCADE
        ///
        ///ALTER TABLE [GroupApplications]  WITH CHECK ADD  CONSTRAINT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string U0006 {
            get {
                return ResourceManager.GetString("U0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 14th Apr, 2014
        ///-- Adam Galloway
        ///-- Create GroupUsers Table
        ///
        ///CREATE TABLE [GroupUsers](
        ///	[GroupId] [int] NOT NULL,
        ///	[UserId] [int] NOT NULL,
        ///	CONSTRAINT [PK_GroupUsers] PRIMARY KEY CLUSTERED ( [GroupId] ASC, [UserId] ASC )
        ///)
        ///
        ///ALTER TABLE [GroupUsers]  WITH CHECK ADD  CONSTRAINT [FK_GroupUsers_Groups] FOREIGN KEY([GroupId])
        ///REFERENCES [Groups] ([Id]) ON DELETE CASCADE
        ///
        ///ALTER TABLE [GroupUsers]  WITH CHECK ADD  CONSTRAINT [FK_GroupUsers_Users] FOREIGN KEY([UserId])
        ///REFERENCES [Users] ([Id]) ON [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string U0007 {
            get {
                return ResourceManager.GetString("U0007", resourceCulture);
            }
        }
    }
}
